"""CodeGen script for generating Airflow DAG wrapper files from compiled JSON configurations."""

import argparse
from pathlib import Path

# Paths relative to the repository root
REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
DEFAULT_CONFIGS_DIR = REPO_ROOT / "configs" / "dags"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "dags"

TEMPLATE = '''# Generated by AI AutoRCA platform codegen. DO NOT EDIT.
"""Airflow DAG wrapper generated from {dag_id}.json."""

from pathlib import Path

from autorca_platform.factory.dag_builder import AirflowDagBuilder
from autorca_platform.metadata.loader import JsonMetadataLoader

# Resolve compiled metadata path relative to this file
METADATA_PATH = Path(__file__).resolve().parent.parent / "configs" / "dags" / "{json_filename}"

loader = JsonMetadataLoader()
metadata = loader.load_dag_config(METADATA_PATH)

builder = AirflowDagBuilder()
dag = builder.build(metadata)
'''


def generate_dags(configs_dir: Path, output_dir: Path) -> None:
    """Generate Airflow DAG wrapper files from JSON configs.

    Args:
        configs_dir: Directory containing compiled JSON configs.
        output_dir: Directory where DAG wrapper files will be written.
    """

    if not configs_dir.exists():
        raise FileNotFoundError(f"Configs directory does not exist: {configs_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)

    config_paths = list(configs_dir.glob("*.json"))
    if not config_paths:
        print(f"No JSON configuration files found in {configs_dir}")
        return

    print(f"Generating {len(config_paths)} DAG wrapper files to {output_dir}...")

    for path in config_paths:
        dag_id = path.stem.upper()
        json_filename = path.name

        output_filename = f"{path.stem.lower()}.py"
        output_path = output_dir / output_filename

        content = TEMPLATE.format(dag_id=dag_id, json_filename=json_filename)

        output_path.write_text(content, encoding="utf-8")

    print("DAG generation completed successfully.")


def main() -> None:
    """CLI entry point for DAG generation."""

    parser = argparse.ArgumentParser(description="Generate Airflow DAG wrapper files from JSON configs.")
    parser.add_argument(
        "--configs-dir",
        type=Path,
        default=DEFAULT_CONFIGS_DIR,
        help="Directory containing compiled JSON configs.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory to write DAG wrapper files.",
    )
    args = parser.parse_args()

    generate_dags(args.configs_dir, args.output_dir)


if __name__ == "__main__":
    main()
