# Generated by AI AutoRCA platform codegen. DO NOT EDIT.
"""Airflow DAG wrapper generated from RTL_RET_ULRJ.json."""

from pathlib import Path

from autorca_platform.factory.dag_builder import AirflowDagBuilder
from autorca_platform.metadata.loader import JsonMetadataLoader

# Resolve compiled metadata path relative to this file
METADATA_PATH = Path(__file__).resolve().parent.parent / "configs" / "dags" / "rtl_ret_ulrj.json"

loader = JsonMetadataLoader()
metadata = loader.load_dag_config(METADATA_PATH)

builder = AirflowDagBuilder()
dag = builder.build(metadata)
