dags:
  persistence:
    enabled: false
  mountPath: /opt/airflow/dags/repo
  gitSync:
    enabled: true
    repo: https://github.com/Pallavi-AI-hub/DAG.git
    branch: main
    ref: main
    rev: HEAD
    subPath: ""
    depth: 1
    period: 30s

env:
  - name: AIRFLOW__CORE__DAGS_FOLDER
    value: /opt/airflow/dags/repo/repo/dags
  - name: PYTHONPATH
    value: /opt/airflow/dags/repo/repo/src
