"""Loader for compiled JSON metadata artifacts."""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import ValidationError

from autorca_platform.core.exceptions import MetadataValidationError
from autorca_platform.metadata.models import DagConfig, GlobalConfig
from autorca_platform.metadata.schema_version import COMPILED_METADATA_SCHEMA_VERSION


class JsonMetadataLoader:
    """Load compiled JSON metadata generated by ``MetadataCompiler``."""

    def load_dag_config(self, path: Path) -> DagConfig:
        """Load one compiled DAG config.

        Args:
            path: JSON config path.

        Returns:
            Parsed DAG config.
        """

        return _load_json_model(path, DagConfig)

    def load_global_config(self, path: Path) -> GlobalConfig:
        """Load compiled global config.

        Args:
            path: JSON config path.

        Returns:
            Parsed global config.
        """

        return _load_json_model(path, GlobalConfig)


def _load_json_model(path: Path, model_type: type[DagConfig] | type[GlobalConfig]) -> DagConfig | GlobalConfig:
    """Load and validate a JSON model."""

    if not path.exists():
        raise MetadataValidationError(f"Compiled metadata file does not exist: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        schema_version = payload.get("schema_version")
        if schema_version != COMPILED_METADATA_SCHEMA_VERSION:
            raise MetadataValidationError(
                f"Unsupported compiled metadata schema version '{schema_version}' in {path}; "
                f"expected '{COMPILED_METADATA_SCHEMA_VERSION}'."
            )
        return model_type.model_validate(payload)
    except json.JSONDecodeError as exc:
        raise MetadataValidationError(f"Compiled metadata file is not valid JSON: {path}") from exc
    except ValidationError as exc:
        raise MetadataValidationError(f"Compiled metadata validation failed for {path}:\n{exc}") from exc
